# locators/common.toml

[common]
ejecutar       = "[id='M0:50::btn[8]']"
continuar      = "[id='M1:50::btn[0]']"
# El ID de la barra de estado suele ser este:
status_bar     = "[id='M0:50::status']"

# Role y títulos
dialog_continuar= "div[role='button'][title='Continuar']" # El botón OK suele ser el de 'Continuar'
ejecutar_title	= "div[role='button'][title*='Ejecutar']" # F8

# Botón OK del diálogo de descarga/confirmación
dialog_ok      = "[id='UpDownDialogChoose']"
# No se usan por ahora:
# popupDialogInputField	= "#popupDialogInputField" # Este es el ID del campo de entrada en el diálogo de descarga
# popupDialogChoose		= "#UpDownDialogChoose" # Este es el ID del diálogo de confirmación de descarga