# locators/common.toml

[common]
# Botones principales
traer_variante  = "role=button[name='Traer variante...']"
mios            = "role=button[name='Propia']"
mios_fallback   = "role=button[title='Creados/Modificados por mí']" # Mejor opción si el name no es único

# Botones de la barra de herramientas (toolbar)

# Línea correcta
ejecutar		= "role=button[name*='Ejecutar']"
continuar		= "role=button[name='Continuar']" # Asumido en base a tu otro botón
# El ID de la barra de estado suele ser este:
status_bar		= "role=status" # Esto es mucho más fiable que un ID

# Role y títulos
dialog_continuar= "role=button[name='Continuar']"
ejecutar_title  = "role=button[title*='Ejecutar']"

# Botón OK del diálogo de descarga/confirmación
dialog_ok      = "role=button[name='OK']"


# Locators para el componente menu_export_dialog
[menu_export_dialog]
radio_texto_con_tabuladores = "role=radio[name='Texto con tabuladores']"
boton_continuar = "role=button[name='Continuar']"
formato_dropdown = "role=combobox[name='Formato']"
guardar_como_textbox = "role=textbox[name='Guardar como :']"
opcion_hoja_calculo = "role=option[name='Archivos de hoja de cálculo (*.xlsx)']"
boton_ok = "role=button[name='OK']"