# locators/login.toml
# Locators para la página de Login de SAP

[form]
input_user		= "role=textbox[name*='Usuario Obligatorio']"
#input_user     = "#sap-user"
input_password = "#sap-password"
input_login    = "#LOGON_BUTTON"