from typing import Protocol

class IPage(Protocol):
    def close(self) -> None: ...
    def is_closed(self) -> bool: ...

class IBrowser(Protocol):
    def new_page(self) -> IPage: ...
    def close(self) -> None: ...
    def is_connected(self) -> bool: ...

class IBrowserFactory(Protocol):
    def create_browser(self) -> IBrowser: ...
