name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - name: Actualizar Código
        run: |
          cd /home/covi/Desarrollo/Scripting/Python/SAP/sap_automation
          git pull
