name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Actualizar Código
        run: |
          cd /home/covi/Desarrollo/Scripting/Python/SAP/sap_automation
          git pull
